// Builds the icon sprite of the design system from the names listed in `icon-names.ts`.
//
// Each icon has its source in `icons/<name>.svg`: Material Symbols Rounded, weight 400, optical size
// 24, unfilled, as in the wireframes. A name without a source is downloaded once from Google Fonts,
// then committed with the rest.
// `--check` fails instead of writing when the committed sprite is out of date, without the network.
import { createHash } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const namesFile = join(root, 'src/lib/icon/icon-names.ts')
const sources = join(root, 'icons')
const spriteFile = join(root, 'src/assets/icons.svg')
const urlFile = join(root, 'src/lib/icon/icon-sprite.ts')
const check = process.argv.includes('--check')

const names = [...readFileSync(namesFile, 'utf8').matchAll(/^\s*'([a-z0-9_]+)',$/gm)].map((match) => match[1])
if (names.length === 0) throw new Error(`No icon name found in ${namesFile}`)

const download = async (name) => {
  const url = `https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded/${name}/default/24px.svg`
  const response = await fetch(url)
  if (!response.ok) throw new Error(`No Material Symbols Rounded icon named "${name}" (${response.status})`)
  writeFileSync(join(sources, `${name}.svg`), await response.text())
  console.log(`Downloaded ${name}.svg`)
}

const missing = names.filter((name) => !existsSync(join(sources, `${name}.svg`)))
if (missing.length && check) {
  console.error(`Icons without a source: ${missing.join(', ')}. Run \`yarn nx run design-system:icons\`.`)
  process.exit(1)
}
for (const name of missing) await download(name)

const symbols = names.map((name) => {
  const svg = readFileSync(join(sources, `${name}.svg`), 'utf8')
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]
  const body = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/)?.[1]
  if (!viewBox || !body) throw new Error(`Unreadable icon: ${name}`)
  return `<symbol id="${name}" viewBox="${viewBox}">${body.trim()}</symbol>`
})

const sprite = `<svg xmlns="http://www.w3.org/2000/svg">\n${symbols.join('\n')}\n</svg>\n`
const version = createHash('sha256').update(sprite).digest('hex').slice(0, 10)
const url = [
  '// Generated by `yarn nx run design-system:icons` from icon-names.ts. The version makes browsers fetch a changed sprite.',
  `export const ICON_SPRITE_URL = 'assets/design-system/icons.svg?v=${version}'`,
  '',
].join('\n')

if (check) {
  const stale = [
    [spriteFile, sprite],
    [urlFile, url],
  ].filter(([file, content]) => !existsSync(file) || readFileSync(file, 'utf8') !== content)
  if (stale.length) {
    console.error('The icon sprite is out of date: run `yarn nx run design-system:icons`.')
    process.exit(1)
  }
  console.log(`Icon sprite up to date (${names.length} icons).`)
} else {
  writeFileSync(spriteFile, sprite)
  writeFileSync(urlFile, url)
  console.log(`Icon sprite written: ${names.length} icons, version ${version}.`)
}
