export enum ResourceEventTypes {
  MEMBER_CREATE = 'MEMBER_CREATE',
  MEMBER_REMOVE = 'MEMBER_REMOVE',
  RESOURCE_CREATE = 'RESOURCE_CREATE',
  RESOURCE_STATUS_CHANGE = 'RESOURCE_STATUS_CHANGE',
  RESOURCE_FILE_CHANGE = 'RESOURCE_FILE_CHANGE',
}
