export enum AdminRoles {
  SysAdmin = 'urn:lti:sysrole:ims/lis/SysAdmin',
  AccountAdmin = 'urn:lti:sysrole:ims/lis/AccountAdmin',
  Manager = 'urn:lti:role:ims/lis/Manager',
  ManagerAreaManager = 'urn:lti:role:ims/lis/Manager/AreaManager',
  ManagerCourseCoordinator = 'urn:lti:role:ims/lis/Manager/CourseCoordinator',
  ManagerObserver = 'urn:lti:role:ims/lis/Manager/Observer',
  ManagerExternalObserver = 'urn:lti:role:ims/lis/Manager/ExternalObserver',
  Administrator = 'urn:lti:sysrole:ims/lis/Administrator',
  Administrator2 = 'urn:lti:instrole:ims/lis/Administrator',
  Administrator3 = 'urn:lti:role:ims/lis/Administrator',
  AdministratorAdministrator = 'urn:lti:role:ims/lis/Administrator/Administrator',
  AdministratorSupport = 'urn:lti:role:ims/lis/Administrator/Support',
  AdministratorDeveloper = 'urn:lti:role:ims/lis/Administrator/Developer',
  AdministratorSystemAdministrator = 'urn:lti:role:ims/lis/Administrator/SystemAdministrator',
  AdministratorExternalSystemAdministrator = 'urn:lti:role:ims/lis/Administrator/ExternalSystemAdministrator',
  AdministratorExternalDeveloper = 'urn:lti:role:ims/lis/Administrator/ExternalDeveloper',
  AdministratorExternalSupport = 'urn:lti:role:ims/lis/Administrator/ExternalSupport',
}

export enum InstructorRoles {
  Faculty = 'urn:lti:instrole:ims/lis/Faculty',
  Staff = 'urn:lti:instrole:ims/lis/Staff',
  Alumni = 'urn:lti:instrole:ims/lis/Alumni',
  Instructor = 'urn:lti:instrole:ims/lis/Instructor',
  Instructor2 = 'urn:lti:role:ims/lis/Instructor',
  Instructor3 = 'Instructor',
  InstructorPrimaryInstructor = 'urn:lti:role:ims/lis/Instructor/PrimaryInstructor',
  InstructorLecturer = 'urn:lti:role:ims/lis/Instructor/Lecturer',
  InstructorGuestInstructor = 'urn:lti:role:ims/lis/Instructor/GuestInstructor',
  InstructorExternalInstructor = 'urn:lti:role:ims/lis/Instructor/ExternalInstructor',
  ContentDeveloper = 'urn:lti:role:ims/lis/ContentDeveloper',
  ContentDeveloperContentDeveloper = 'urn:lti:role:ims/lis/ContentDeveloper/ContentDeveloper',
  ContentDeveloperLibrarian = 'urn:lti:role:ims/lis/ContentDeveloper/Librarian',
  ContentDeveloperContentExpert = 'urn:lti:role:ims/lis/ContentDeveloper/ContentExpert',
  ContentDeveloperExternalContentExpert = 'urn:lti:role:ims/lis/ContentDeveloper/ExternalContentExpert',
}

export enum ReviewerRoles {
  SysSupport = 'urn:lti:sysrole:ims/lis/SysSupport',
  Creator = 'urn:lti:sysrole:ims/lis/Creator',
  Observer = 'urn:lti:instrole:ims/lis/Observer',
  Mentor = 'urn:lti:instrole:ims/lis/Mentor',
  Mentor2 = 'urn:lti:role:ims/lis/Mentor',
  MentorMentor = 'urn:lti:role:ims/lis/Mentor/Mentor',
  MentorReviewer = 'urn:lti:role:ims/lis/Mentor/Reviewer',
  MentorAdvisor = 'urn:lti:role:ims/lis/Mentor/Advisor',
  MentorAuditor = 'urn:lti:role:ims/lis/Mentor/Auditor',
  MentorTutor = 'urn:lti:role:ims/lis/Mentor/Tutor',
  MentorLearningFacilitator = 'urn:lti:role:ims/lis/Mentor/LearningFacilitator',
  MentorExternalMentor = 'urn:lti:role:ims/lis/Mentor/ExternalMentor',
  MentorExternalReviewer = 'urn:lti:role:ims/lis/Mentor/ExternalReviewer',
  MentorExternalAdvisor = 'urn:lti:role:ims/lis/Mentor/ExternalAdvisor',
  MentorExternalAuditor = 'urn:lti:role:ims/lis/Mentor/ExternalAuditor',
  MentorExternalTutor = 'urn:lti:role:ims/lis/Mentor/ExternalTutor',
  MentorExternalLearningFacilitator = 'urn:lti:role:ims/lis/Mentor/ExternalLearningFacilitator',
  TeachingAssistant = 'urn:lti:role:ims/lis/TeachingAssistant',
  TeachingAssistantTeachingAssistant = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistant',
  TeachingAssistantTeachingAssistantSection = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantSection',
  TeachingAssistantTeachingAssistantSectionAssociation = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantSectionAssociation',
  TeachingAssistantTeachingAssistantOffering = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantOffering',
  TeachingAssistantTeachingAssistantTemplate = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantTemplate',
  TeachingAssistantTeachingAssistantGroup = 'urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantGroup',
  TeachingAssistantGrader = 'urn:lti:role:ims/lis/TeachingAssistant/Grader',
}

export enum StudentRoles {
  User = 'urn:lti:sysrole:ims/lis/User',
  Student = 'urn:lti:instrole:ims/lis/Student',
  Learner = 'urn:lti:instrole:ims/lis/Learner',
  Learner2 = 'urn:lti:role:ims/lis/Learner',
  Guest = 'urn:lti:instrole:ims/lis/Guest',
  ProspectiveStudent = 'urn:lti:instrole:ims/lis/ProspectiveStudent',
  LearnerLearner = 'urn:lti:role:ims/lis/Learner/Learner',
  LearnerNonCreditLearner = 'urn:lti:role:ims/lis/Learner/NonCreditLearner',
  LearnerGuestLearner = 'urn:lti:role:ims/lis/Learner/GuestLearner',
  LearnerExternalLearner = 'urn:lti:role:ims/lis/Learner/ExternalLearner',
  LearnerInstructor = 'urn:lti:role:ims/lis/Learner/Instructor',
  Member = 'urn:lti:role:ims/lis/Member',
  MemberMember = 'urn:lti:role:ims/lis/Member/Member',
  Other = 'urn:lti:instrole:ims/lis/Other',
}

export declare type LTIRoles = AdminRoles | InstructorRoles | ReviewerRoles | StudentRoles
