FROM nginx

RUN rm /etc/nginx/conf.d/default.conf

COPY .docker/nginx/nginx.dev.conf /etc/nginx/nginx.conf
COPY .docker/nginx/ssl/dhparam/dhparam.pem /etc/nginx/dhparam.pem
COPY .docker/nginx/ssl/certs/localhost.crt /etc/nginx/ssl/localhost.crt
COPY .docker/nginx/ssl/certs/localhost.key /etc/nginx/ssl/localhost.key

# Forward nginx logs to docker
# https://alexanderallen.medium.com/forwarding-nginx-logs-to-docker-3bb6283a207
RUN ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log
