export * from './lib/docs/docs'
export * from './lib/web-component.module'
export * from './lib/web-component'
export * from './lib/web-component-registry'
export * from './lib/web-component.service'
