name: CI

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  prepare:
      name: Prepare
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - uses: ./.github/actions/yarn-setup

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/yarn-setup

      - name: 'NX: SHAs for affected'
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref || github.ref_name }}

      - name: Generate Graphql Types
        shell: bash
        run: ./bin/graphql/generate.sh

      - run: yarn affected:build --parallel --base=${{ env.NX_BASE }}

      - name: Build Storybook of the design system
        run: yarn nx affected --target=build-storybook --base=${{ env.NX_BASE }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/yarn-setup

      - name: 'NX: SHAs for affected'
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref || github.ref_name }}

      - run: yarn affected:lint --parallel --base=${{ env.NX_BASE }}

      - name: Design lints of the new interface
        run: yarn lint:design

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/yarn-setup

      - name: 'NX: SHAs for affected'
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref || github.ref_name }}

      - run: yarn affected:test --parallel --base=${{ env.NX_BASE }}

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  test-integration:
    name: Test Integration
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/yarn-setup

      - name: 'NX: SHAs for affected'
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref || github.ref_name }}

      - name: Run integration tests on affected projects
        run: yarn affected:test:integration --base=${{ env.NX_BASE }}

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/yarn-setup

      - name: 'NX: SHAs for affected'
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref || github.ref_name }}

      - name: Run e2e tests on affected projects
        run: yarn affected:test:e2e --base=${{ env.NX_BASE }}
